# This is a basic workflow to test the wine queries

name: Test Queries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./cms_exercises
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install rdflib
        run: |
          python -m pip install --upgrade pip
          python -m pip install rdflib
          python -m pip install requests

      - name: Run test script
        run: python -m unittest wine_tests.py
